/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ImagenControl;
import Modelo.Imagen;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.imgscalr.Scalr;

/**
 *
 * @author ABEL
 */
public class ImagenVista extends javax.swing.JFrame {

    ImagenControl imagencontrol;

    /**
     * Creates new form ImagenVista
     */
    public ImagenVista() {
        initComponents();
        imagencontrol = new ImagenControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        panelImagen = new javax.swing.JPanel();
        botonAtras = new javax.swing.JButton();
        casilla1 = new javax.swing.JLabel();
        casilla2 = new javax.swing.JLabel();
        casilla3 = new javax.swing.JLabel();
        botonAdelante = new javax.swing.JButton();
        imagePanel = new Vista.ImagePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cargarImg = new javax.swing.JMenu();
        cargarImagen = new javax.swing.JMenuItem();
        saveIteam = new javax.swing.JMenuItem();
        loadItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAtras.setText("<");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        panelImagen.add(botonAtras);

        casilla1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        casilla1.setMaximumSize(new java.awt.Dimension(20, 20));
        casilla1.setMinimumSize(new java.awt.Dimension(20, 20));
        casilla1.setPreferredSize(new java.awt.Dimension(20, 20));
        panelImagen.add(casilla1);

        casilla2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        casilla2.setMaximumSize(new java.awt.Dimension(20, 20));
        casilla2.setMinimumSize(new java.awt.Dimension(20, 20));
        casilla2.setPreferredSize(new java.awt.Dimension(20, 20));
        panelImagen.add(casilla2);

        casilla3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        casilla3.setMaximumSize(new java.awt.Dimension(20, 20));
        casilla3.setMinimumSize(new java.awt.Dimension(20, 20));
        casilla3.setPreferredSize(new java.awt.Dimension(20, 20));
        panelImagen.add(casilla3);

        botonAdelante.setText(">");
        botonAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdelanteActionPerformed(evt);
            }
        });
        panelImagen.add(botonAdelante);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        cargarImg.setText("File");
        cargarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImgActionPerformed(evt);
            }
        });

        cargarImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\dam2\\Documents\\GitHub\\CarruselAbel\\src\\main\\resources\\imagenes\\add.png")); // NOI18N
        cargarImagen.setText("Add");
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });
        cargarImg.add(cargarImagen);

        saveIteam.setIcon(new javax.swing.ImageIcon("C:\\Users\\dam2\\Documents\\GitHub\\CarruselAbel\\src\\main\\resources\\imagenes\\save.png")); // NOI18N
        saveIteam.setText("Save");
        saveIteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIteamActionPerformed(evt);
            }
        });
        cargarImg.add(saveIteam);

        loadItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\dam2\\Documents\\GitHub\\CarruselAbel\\src\\main\\resources\\imagenes\\load.png")); // NOI18N
        loadItem.setText("Load");
        cargarImg.add(loadItem);

        jMenuBar1.add(cargarImg);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImgActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cargarImgActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
        fileChooser.showOpenDialog(this);

        imagencontrol.addImagen(new Imagen(fileChooser.getSelectedFile().getPath()));

        pintarArrayImagen();
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void botonAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdelanteActionPerformed
        // TODO add your handling code here:
        imagencontrol.siguienteImagen();
        pintarArrayImagen();
    }//GEN-LAST:event_botonAdelanteActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        imagencontrol.atrasImagen();
        pintarArrayImagen();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void saveIteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIteamActionPerformed
        // TODO add your handling code here:
        //imagencontrol.saveImagen();
    }//GEN-LAST:event_saveIteamActionPerformed

    public void pintarArrayImagen() {
        BufferedImage ima;
        try {
            switch (imagencontrol.getTamaño()) {

                default:
                    ima = ImageIO.read(new File(imagencontrol.getBackCurrentImagen().getPathImagen()));
                    casilla1.setIcon(new ImageIcon(ima.getScaledInstance(imagencontrol.getBackCurrentImagen().getWidthIcono(), imagencontrol.getBackCurrentImagen().getHeightIcono(), Image.SCALE_DEFAULT)));
                    ;
                case 2:
                    ima = ImageIO.read(new File(imagencontrol.getNextCurrentImagen().getPathImagen()));
                    casilla3.setIcon(new ImageIcon(ima.getScaledInstance(imagencontrol.getNextCurrentImagen().getWidthIcono(), imagencontrol.getNextCurrentImagen().getHeightIcono(), Image.SCALE_DEFAULT)));
                case 1:
                    ima = ImageIO.read(new File(imagencontrol.getCurrentImagen().getPathImagen()));
                    casilla2.setIcon(new ImageIcon(ima.getScaledInstance(imagencontrol.getCurrentImagen().getWidthIcono(), imagencontrol.getCurrentImagen().getHeightIcono(), Image.SCALE_DEFAULT)));
                    BufferedImage im = ImageIO.read(new File(imagencontrol.getCurrentImagen().getPathImagen()));
                    imagePanel.setImagen(Scalr.resize(im, Scalr.Mode.AUTOMATIC, imagencontrol.getCurrentImagen().getWidthGrande(), imagencontrol.getCurrentImagen().getHeightGrande(), null));
            }
        } catch (IOException ex) {
            Logger.getLogger(ImagenVista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagenVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdelante;
    private javax.swing.JButton botonAtras;
    private javax.swing.JMenuItem cargarImagen;
    private javax.swing.JMenu cargarImg;
    private javax.swing.JLabel casilla1;
    private javax.swing.JLabel casilla2;
    private javax.swing.JLabel casilla3;
    private javax.swing.JFileChooser fileChooser;
    private Vista.ImagePanel imagePanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadItem;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JMenuItem saveIteam;
    // End of variables declaration//GEN-END:variables
}
